#!/usr/bin/env bash
# simpleviz installer — installs the latest GitHub release into
# ~/.simpleviz (a directory this installer fully manages: reinstalls
# replace it) and a launcher into ~/.local/bin/simpleviz.
#
#   curl -fsSL https://raw.githubusercontent.com/sstoehrm/simpleviz/main/install.sh | bash
#
# Env overrides: SIMPLEVIZ_HOME (default ~/.simpleviz),
#                SIMPLEVIZ_BIN  (default ~/.local/bin)
set -euo pipefail

REPO="sstoehrm/simpleviz"
API_URL="https://api.github.com/repos/$REPO/releases/latest"
SIMPLEVIZ_HOME="${SIMPLEVIZ_HOME:-$HOME/.simpleviz}"
BIN_DIR="${SIMPLEVIZ_BIN:-$HOME/.local/bin}"
MIN_BB="1.3.0"

die() { echo "install: $*" >&2; exit 1; }

check_deps() {
  local c have
  for c in curl tar; do
    command -v "$c" >/dev/null 2>&1 || die "$c is required"
  done
  command -v bb >/dev/null 2>&1 \
    || die "babashka (bb) not found — install it from https://babashka.org"
  have=$(bb --version | sed -E 's/[^0-9.]//g')
  [ "$(printf '%s\n' "$MIN_BB" "$have" | sort -V | head -n1)" = "$MIN_BB" ] \
    || die "babashka $have is too old (need >= $MIN_BB)"
}

fetch_release() { # sets TAG and TARBALL_URL
  local json
  json=$(curl -fsSL "$API_URL") || die "could not query $API_URL"
  TAG=$(grep -m1 '"tag_name"' <<<"$json" | sed -E 's/.*: *"([^"]+)".*/\1/')
  TARBALL_URL=$(grep -m1 -o '"browser_download_url" *: *"[^"]*\.tar\.gz"' <<<"$json" \
                | sed -E 's/.*"(https[^"]+)".*/\1/')
  [ -n "$TAG" ] && [ -n "$TARBALL_URL" ] \
    || die "no .tar.gz asset found in the latest release"
}

install_files() {
  local dir
  # deliberately not `local`: the EXIT trap runs after this function's
  # scope is gone, so the variable must survive it
  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' EXIT
  echo "downloading $TARBALL_URL"
  curl -fsSL "$TARBALL_URL" -o "$tmp/bundle.tar.gz"
  tar xzf "$tmp/bundle.tar.gz" -C "$tmp"
  dir=$(find "$tmp" -mindepth 1 -maxdepth 1 -type d | head -n1)
  [ -n "$dir" ] || die "unexpected tarball layout (no top-level directory)"
  rm -rf "$SIMPLEVIZ_HOME"
  mkdir -p "$SIMPLEVIZ_HOME"
  cp -R "$dir"/. "$SIMPLEVIZ_HOME"/
  echo "$TAG" >"$SIMPLEVIZ_HOME/VERSION"
  # keep a copy of this installer for `simpleviz update`; when run via
  # `curl | bash` there is no file on disk, so fetch it from the repo
  if [ -f "${BASH_SOURCE[0]:-}" ]; then
    cp "${BASH_SOURCE[0]}" "$SIMPLEVIZ_HOME/install.sh"
  else
    curl -fsSL "https://raw.githubusercontent.com/$REPO/main/install.sh" \
      -o "$SIMPLEVIZ_HOME/install.sh" \
      || echo "note: could not store installer copy; 'simpleviz update' will not work" >&2
  fi
  [ -f "$SIMPLEVIZ_HOME/install.sh" ] && chmod +x "$SIMPLEVIZ_HOME/install.sh"
}

write_launcher() {
  mkdir -p "$BIN_DIR"
  cat >"$BIN_DIR/simpleviz" <<'LAUNCHER'
#!/usr/bin/env bash
# simpleviz launcher — generated by install.sh; reinstalling overwrites it.
set -euo pipefail

SIMPLEVIZ_HOME="${SIMPLEVIZ_HOME:-$HOME/.simpleviz}"
API_URL="https://api.github.com/repos/sstoehrm/simpleviz/releases/latest"
MIN_BB="1.3.0"

usage() {
  cat <<USAGE
usage: simpleviz <graph.edn> [new.edn]   serve a graph (two files: compare old -> new)
       simpleviz update                  install the latest release if it is newer
       simpleviz --version               print the installed version
Serves on a random free port between 7370 and 7379.
Try the bundled example: simpleviz "$SIMPLEVIZ_HOME/examples/demo.edn"
USAGE
}

die() { echo "simpleviz: $*" >&2; exit 1; }

check_bb() {
  local have
  command -v bb >/dev/null 2>&1 \
    || die "babashka (bb) not found — install it from https://babashka.org"
  have=$(bb --version | sed -E 's/[^0-9.]//g')
  [ "$(printf '%s\n' "$MIN_BB" "$have" | sort -V | head -n1)" = "$MIN_BB" ] \
    || die "babashka $have is too old (need >= $MIN_BB)"
}

version() { cat "$SIMPLEVIZ_HOME/VERSION" 2>/dev/null || echo "unknown"; }

update() {
  local latest
  latest=$(curl -fsSL "$API_URL" | grep -m1 '"tag_name"' \
           | sed -E 's/.*: *"([^"]+)".*/\1/') \
    || die "could not query the latest release"
  [ -n "$latest" ] || die "could not read the latest release tag"
  if [ "$latest" = "$(version)" ]; then
    echo "simpleviz $(version) is already up to date"
  elif [ -f "$SIMPLEVIZ_HOME/install.sh" ]; then
    echo "updating $(version) -> $latest"
    SIMPLEVIZ_HOME="$SIMPLEVIZ_HOME" bash "$SIMPLEVIZ_HOME/install.sh"
  else
    die "no stored installer at $SIMPLEVIZ_HOME/install.sh — re-run install.sh manually"
  fi
}

port_busy() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null; }

free_port() {
  local p
  for p in $(shuf -i 7370-7379); do
    port_busy "$p" || { echo "$p"; return 0; }
  done
  return 1
}

serve() {
  local files=() f port pid i
  [ -d "$SIMPLEVIZ_HOME" ] || die "$SIMPLEVIZ_HOME not found — run install.sh first"
  for f in "$@"; do
    [ -f "$f" ] || die "file not found: $f"
    files+=("$(realpath "$f")")
  done
  check_bb
  port=$(free_port) || die "no free port between 7370 and 7379"
  (cd "$SIMPLEVIZ_HOME" && exec bb serve "${files[@]}" --port "$port") &
  pid=$!
  trap 'kill "$pid" 2>/dev/null || true' INT TERM
  for i in $(seq 1 100); do
    port_busy "$port" && break
    kill -0 "$pid" 2>/dev/null || die "server exited before accepting connections"
    sleep 0.1
  done
  echo "simpleviz: http://localhost:$port"
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "http://localhost:$port" >/dev/null 2>&1 || true
  fi
  wait "$pid"
}

case "${1:-}" in
  "" | -h | --help) usage ;;
  --version | version) echo "simpleviz $(version)" ;;
  update) update ;;
  *)
    [ "$#" -le 2 ] || { usage >&2; exit 1; }
    serve "$@"
    ;;
esac
LAUNCHER
  chmod +x "$BIN_DIR/simpleviz"
}

main() {
  check_deps
  fetch_release
  install_files
  write_launcher
  case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "note: $BIN_DIR is not on your PATH — add it to use 'simpleviz'" ;;
  esac
  echo "installed simpleviz $TAG"
  echo "  files:    $SIMPLEVIZ_HOME"
  echo "  launcher: $BIN_DIR/simpleviz"
  echo "try: simpleviz $SIMPLEVIZ_HOME/examples/demo.edn"
}

if [ "${SIMPLEVIZ_INSTALL_SOURCED:-}" != "1" ]; then
  main "$@"
fi
