#!/usr/bin/env bash
# simpleviz installer — installs the latest GitHub release into
# ~/.simpleviz (a directory this installer fully manages: reinstalls
# replace it) and a launcher into ~/.local/bin/simpleviz.
#
#   curl -fsSL https://raw.githubusercontent.com/sstoehrm/simpleviz/main/install.sh | bash
#
# Env overrides: SIMPLEVIZ_HOME (default ~/.simpleviz),
#                SIMPLEVIZ_BIN  (default ~/.local/bin)
set -euo pipefail

REPO="sstoehrm/simpleviz"
API_URL="https://api.github.com/repos/$REPO/releases/latest"
SIMPLEVIZ_HOME="${SIMPLEVIZ_HOME:-$HOME/.simpleviz}"
BIN_DIR="${SIMPLEVIZ_BIN:-$HOME/.local/bin}"
MIN_BB="1.3.0"

die() { echo "install: $*" >&2; exit 1; }

check_deps() {
  local c have
  for c in curl tar; do
    command -v "$c" >/dev/null 2>&1 || die "$c is required"
  done
  command -v bb >/dev/null 2>&1 \
    || die "babashka (bb) not found — install it from https://babashka.org"
  have=$(bb --version | sed -E 's/[^0-9.]//g')
  [ "$(printf '%s\n' "$MIN_BB" "$have" | sort -V | head -n1)" = "$MIN_BB" ] \
    || die "babashka $have is too old (need >= $MIN_BB)"
}

fetch_release() { # sets TAG and TARBALL_URL
  local json
  json=$(curl -fsSL "$API_URL") || die "could not query $API_URL"
  TAG=$(grep -m1 '"tag_name"' <<<"$json" | sed -E 's/.*: *"([^"]+)".*/\1/' || true)
  TARBALL_URL=$(grep -m1 -o '"browser_download_url" *: *"[^"]*\.tar\.gz"' <<<"$json" \
                | sed -E 's/.*"(https[^"]+)".*/\1/' || true)
  [ -n "$TAG" ] && [ -n "$TARBALL_URL" ] \
    || die "no .tar.gz asset found in the latest release"
}

install_files() {
  local dir
  # deliberately not `local`: the EXIT trap runs after this function's
  # scope is gone, so the variable must survive it
  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' EXIT
  echo "downloading $TARBALL_URL"
  curl -fsSL "$TARBALL_URL" -o "$tmp/bundle.tar.gz"
  tar xzf "$tmp/bundle.tar.gz" -C "$tmp"
  dir=$(find "$tmp" -mindepth 1 -maxdepth 1 -type d | head -n1)
  [ -n "$dir" ] || die "unexpected tarball layout (no top-level directory)"
  rm -rf "$SIMPLEVIZ_HOME"
  mkdir -p "$SIMPLEVIZ_HOME"
  cp -R "$dir"/. "$SIMPLEVIZ_HOME"/
  echo "$TAG" >"$SIMPLEVIZ_HOME/VERSION"
}

write_launcher() {
  mkdir -p "$BIN_DIR"
  cat >"$BIN_DIR/simpleviz" <<'LAUNCHER'
#!/usr/bin/env bash
# simpleviz launcher — generated by install.sh; reinstalling overwrites it.
set -euo pipefail

SIMPLEVIZ_HOME="${SIMPLEVIZ_HOME:-$HOME/.simpleviz}"
API_URL="https://api.github.com/repos/sstoehrm/simpleviz/releases/latest"
MIN_BB="1.3.0"

usage() {
  cat <<USAGE
usage: simpleviz <graph.edn> [<suffix>] [--debug]   serve a graph; with a suffix, compare it
                                         against its fork graph-<suffix>.edn (refs follow
                                         into the same comparison of each referenced file)
                                         exported PNGs work in place of EDN files
                                         --debug logs edits and errors to $SIMPLEVIZ_HOME/logs/

       simpleviz fork <graph.edn> <suffix>     copy the graph and every file it refs to
                                               <name>-<suffix>.edn siblings
       simpleviz promote <graph.edn> <suffix>  move each fork over its original file
       simpleviz init <graph.edn>        write a starter graph file (won't overwrite)
       simpleviz extract <diagram.png> [out.edn] [--old]   print/extract the embedded EDN
       simpleviz check <graph.edn>       print the parse error or validation warnings
                                         the page would show; exit 1 if there are any
       simpleviz update                  install the latest release if it is newer
       simpleviz clean-all               kill every running simpleviz server
       simpleviz --version               print the installed version
Serves on a random free port between 7370 and 7469.
Try the bundled example: simpleviz "$SIMPLEVIZ_HOME/examples/demo.edn" next
USAGE
}

die() { echo "simpleviz: $*" >&2; exit 1; }

check_bb() {
  local have
  command -v bb >/dev/null 2>&1 \
    || die "babashka (bb) not found — install it from https://babashka.org"
  have=$(bb --version | sed -E 's/[^0-9.]//g')
  [ "$(printf '%s\n' "$MIN_BB" "$have" | sort -V | head -n1)" = "$MIN_BB" ] \
    || die "babashka $have is too old (need >= $MIN_BB)"
}

version() { cat "$SIMPLEVIZ_HOME/VERSION" 2>/dev/null || echo "unknown"; }

init_cmd() {
  [ "$#" -eq 1 ] || { usage >&2; exit 1; }
  local f="$1"
  if [ -e "$f" ]; then
    die "$f already exists"
  fi
  cat >"$f" <<'TEMPLATE'
{:nodes {:web {:name "Web" :type "frontend"}
         :api {:name "API" :type "service"}}
 :edges {[:web :api] {:direction :-> :name "calls" :type "http"}}
 :boxes {:backend {:type "zone" :components #{:api}}}}
TEMPLATE
  echo "created $f — view it with: simpleviz $f"
}

update() {
  local latest installer
  latest=$(curl -fsSL "$API_URL" | grep -m1 '"tag_name"' \
           | sed -E 's/.*: *"([^"]+)".*/\1/') \
    || die "could not query the latest release"
  [ -n "$latest" ] || die "could not read the latest release tag"
  if [ "$latest" = "$(version)" ]; then
    echo "simpleviz $(version) is already up to date"
  else
    echo "updating $(version) -> $latest"
    # run the new release's installer, never a stored copy: an installer
    # writes the launcher embedded in itself, so an old one would keep
    # reinstalling its old launcher next to the new files
    installer=$(mktemp)
    curl -fsSL "https://raw.githubusercontent.com/sstoehrm/simpleviz/$latest/install.sh" \
      -o "$installer" || { rm -f "$installer"; die "could not download the $latest installer"; }
    SIMPLEVIZ_HOME="$SIMPLEVIZ_HOME" bash "$installer"
    rm -f "$installer"
  fi
}

port_busy() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null; }

clean_all() {
  local home procs line pid found=0
  # the launcher always execs `bb serve ...` from inside SIMPLEVIZ_HOME, so
  # the cwd tells our servers apart from any other babashka process
  [ -r /proc/self/cwd ] || die "clean-all needs /proc to inspect processes"
  home=$(readlink -f "$SIMPLEVIZ_HOME")
  procs=$(pgrep -af "(^|/)bb serve( |$)" || true)
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    pid=${line%% *}
    [ "$(readlink "/proc/$pid/cwd" 2>/dev/null)" = "$home" ] || continue
    found=1
    echo "killing ${line#* }"
    kill "$pid" 2>/dev/null || true
  done <<<"$procs"
  [ "$found" -eq 1 ] || echo "simpleviz: no running servers"
}

free_port() {
  local p
  for p in $(shuf -i 7370-7469); do
    port_busy "$p" || { echo "$p"; return 0; }
  done
  return 1
}

fork_name() { # <path> <suffix> -> <dir>/<stem>-<suffix>.<ext>
  local f="$1" s="$2" dir base
  dir=$(dirname "$f"); base=$(basename "$f")
  case "$base" in
    *.*) echo "$dir/${base%.*}-$s.${base##*.}" ;;
    *)   echo "$dir/$base-$s" ;;
  esac
}

serve() {
  local file="" suffix="" flags=() f fork port pid i
  [ -d "$SIMPLEVIZ_HOME" ] || die "$SIMPLEVIZ_HOME not found — run install.sh first"
  for f in "$@"; do
    case "$f" in
      --debug) flags+=("$f") ;;
      *)
        if [ -z "$file" ]; then
          [ -f "$f" ] || die "file not found: $f"
          file=$(realpath "$f")
        elif [ -z "$suffix" ]; then
          case "$f" in
            *.edn|*.EDN|*.png|*.PNG)
              die "two-file compare was replaced: simpleviz fork $file <suffix>, then simpleviz $file <suffix>" ;;
            *[!A-Za-z0-9_.-]*|"")
              die "invalid suffix: $f" ;;
          esac
          suffix="$f"
        else
          usage >&2; exit 1
        fi
        ;;
    esac
  done
  [ -n "$file" ] || { usage >&2; exit 1; }
  if [ -n "$suffix" ]; then
    fork=$(fork_name "$file" "$suffix")
    [ -f "$fork" ] || die "$fork not found — create it with: simpleviz fork $file $suffix"
  fi
  check_bb
  port=$(free_port) || die "no free port between 7370 and 7469"
  (cd "$SIMPLEVIZ_HOME" && exec bb serve "$file" ${suffix:+"$suffix"} --port "$port" ${flags[@]+"${flags[@]}"}) &
  pid=$!
  trap 'kill "$pid" 2>/dev/null || true' INT TERM
  for i in $(seq 1 100); do
    port_busy "$port" && break
    kill -0 "$pid" 2>/dev/null || die "server exited before accepting connections"
    sleep 0.1
  done
  echo "simpleviz: http://localhost:$port"
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "http://localhost:$port" >/dev/null 2>&1 || true
  fi
  wait "$pid"
}

case "${1:-}" in
  "" | -h | --help) usage ;;
  --version | version) echo "simpleviz $(version)" ;;
  update) update ;;
  clean-all) clean_all ;;
  init)
    shift
    init_cmd "$@"
    ;;
  fork | promote)
    cmd="$1"; shift
    [ "$#" -eq 2 ] || { usage >&2; exit 1; }
    [ -f "$1" ] || die "file not found: $1"
    check_bb
    [ -d "$SIMPLEVIZ_HOME" ] || die "$SIMPLEVIZ_HOME not found — run install.sh first"
    file=$(realpath "$1")
    (cd "$SIMPLEVIZ_HOME" && exec bb "$cmd" "$file" "$2")
    ;;
  check)
    shift
    [ "$#" -eq 1 ] || { usage >&2; exit 1; }
    check_bb
    [ -d "$SIMPLEVIZ_HOME" ] || die "$SIMPLEVIZ_HOME not found — run install.sh first"
    file=$(realpath -m -- "$1")
    (cd "$SIMPLEVIZ_HOME" && exec bb check "$file")
    ;;
  extract)
    shift
    check_bb
    [ -d "$SIMPLEVIZ_HOME" ] || die "$SIMPLEVIZ_HOME not found — run install.sh first"
    args=()
    for a in "$@"; do
      case "$a" in
        --old) args+=("$a") ;;
        *) args+=("$(realpath -m "$a")") ;;
      esac
    done
    (cd "$SIMPLEVIZ_HOME" && exec bb extract "${args[@]}")
    ;;
  *)
    serve "$@"
    ;;
esac
LAUNCHER
  chmod +x "$BIN_DIR/simpleviz"
}

main() {
  check_deps
  fetch_release
  install_files
  write_launcher
  case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "note: $BIN_DIR is not on your PATH — add it to use 'simpleviz'" ;;
  esac
  echo "installed simpleviz $TAG"
  echo "  files:    $SIMPLEVIZ_HOME"
  echo "  launcher: $BIN_DIR/simpleviz"
  echo "try: simpleviz $SIMPLEVIZ_HOME/examples/demo.edn"
}

if [ "${SIMPLEVIZ_INSTALL_SOURCED:-}" != "1" ]; then
  main "$@"
fi
